### ISSUE TITLE
音乐播放有点问题

### ISSUE THREAD

**Issue by SuperTian007** [SkillCollege/SimplifyReader#1]
音乐轻听这部分有几个问题：

- 点击下一曲之后，界面就完全卡住了。需要再点一次播放，然后等十几秒，才会真正开始播放下一曲
- 下一曲之后，再点下一曲，依然会遇到刚才的问题，并且并它没有跳到下一曲，而是又会跳回上一曲。
- 拖动进度条没有反应，好像跟音乐没有关系。

手机：一加手机1
系统：氢OS（Android 5.1.1）

**Comment by SkillCollege** [comment]
我的播放逻辑是，点击下一曲从网络请求下一曲的url，可能网络返回比较慢，导致你认为界面卡住了，如果url成功返回就会播放的。另外，跳转到相同的url也是可能会出现的。所以我会继续改进！

**Comment by SuperTian007** [comment]
加油~不过真的是卡住了。。。不动了。。微博上好像也有人提过这个问题，你可以留意一下~

**Comment by SkillCollege** [comment]
好的。。。谢谢你

**Comment by NingSo** [comment]
java.lang.ExceptionInInitializerError
            at com.youku.player.YoukuPlayerBaseApplication.onCreate(YoukuPlayerBaseApplication.java:35)
            at com.github.obsessive.simplifyreader.SimplifyReaderApplication.onCreate(SimplifyReaderApplication.java:38)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1000)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4391)
            at android.app.ActivityThread.access$1300(ActivityThread.java:141)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1294)
            at android.os.Handler.dispatchMessage(Handler.java:99)

**Comment by cha331** [comment]
刚刚加入github终于看到简中感觉好亲切

**Comment by wrjqss** [comment]
播放器的界面没有适配。。放nexus7上  那啥就搭不到磁碟上了
