### ISSUE TITLE
图片未加载完成，点击奔溃

### ISSUE THREAD

**Issue by yangweidong** [SkillCollege/SimplifyReader#2]
java.lang.ClassCastException: android.graphics.drawable.ColorDrawable cannot be cast to android.graphics.drawable.BitmapDrawable
            at com.github.obsessive.library.widgets.SmoothImageView.initTransform(SmoothImageView.java:172)
            at com.github.obsessive.library.widgets.SmoothImageView.onDraw(SmoothImageView.java:279)
            at android.view.View.draw(View.java:14493)

**Comment by SkillCollege** [comment]
报错信息很明显，SmoothImageView的172行，你搜索java.lang.ClassCastException: android.graphics.drawable.ColorDrawable cannot be cast to android.graphics.drawable.BitmapDrawable这个错误应该能解决问题昂
