### ISSUE TITLE
下载apk运行崩溃,log日志如下

### ISSUE THREAD

**Issue by z-chu** [SkillCollege/SimplifyReader#60]
FATAL EXCEPTION: main
Process: com.github.obsessive.simplifyreader.application, PID: 1590
java.lang.UnsatisfiedLinkError:
Couldn't load luajava from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.github.obsessive.simplifyreader-1.apk"],
nativeLibraryDirectories=[/data/app-lib/com.github.obsessive.simplifyreader-1, /system/lib]]]: findLibrary returned null
at java.lang.Runtime.loadLibrary(Runtime.java:358)
at java.lang.System.loadLibrary(System.java:526)
at com.luajava.LuaState.<clinit>(LuaState.java:92)
at com.luajava.LuaStateFactory.newLuaState(LuaStateFactory.java:59)
at com.decapi.DecAPI.<clinit>(DecAPI.java:27)
at com.youku.player.YoukuPlayerBaseApplication.onCreate(YoukuPlayerBaseApplication.java:35)
at com.github.obsessive.simplifyreader.SimplifyReaderApplication.onCreate(SimplifyReaderApplication.java:38)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4328)
at android.app.ActivityThread.access$1500(ActivityThread.java:135)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5001)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
at dalvik.system.NativeStart.main(Native Method)

**Comment by liaopen123** [comment]
+1
