### ISSUE TITLE
最新的包运行出错 找不到 libluajava.so

### ISSUE THREAD

**Issue by elderSword** [SkillCollege/SimplifyReader#65]
FATAL EXCEPTION: main
                                                                                                 Process: com.github.obsessive.simplifyreader.application, PID: 23447
                                                                                                 java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.github.obsessive.simplifyreader-1/base.apk"],nativeLibraryDirectories=[/data/app/com.github.obsessive.simplifyreader-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libluajava.so"
                                                                                                     at java.lang.Runtime.loadLibrary(Runtime.java:367)
                                                                                                     at java.lang.System.loadLibrary(System.java:988)
                                                                                                     at com.luajava.LuaState.<clinit>(LuaState.java:92)
                                                                                                     at com.luajava.LuaStateFactory.newLuaState(LuaStateFactory.java:59)
                                                                                                     at com.decapi.DecAPI.<clinit>(DecAPI.java:27)
                                                                                                     at com.youku.player.YoukuPlayerBaseApplication.onCreate(YoukuPlayerBaseApplication.java:35)
                                                                                                     at com.github.obsessive.simplifyreader.SimplifyReaderApplication.onCreate(SimplifyReaderApplication.java:38)
                                                                                                     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1017)
                                                                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4831)
                                                                                                     at android.app.ActivityThread.access$1600(ActivityThread.java:180)
                                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1548)
                                                                                                     at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                                                     at android.os.Looper.loop(Looper.java:194)
                                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5609)
                                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
                                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)

**Comment by William-Guan** [comment]
FATAL EXCEPTION: main
                                                                                               Process: com.github.obsessive.simplifyreader.application, PID: 1782
                                                                                               java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.github.obsessive.simplifyreader-1/base.apk"],nativeLibraryDirectories=[/data/app/com.github.obsessive.simplifyreader-1/lib/x86, /vendor/lib, /system/lib]]] couldn't find "libluajava.so"
                                                                                                   at java.lang.Runtime.loadLibrary(Runtime.java:366)
                                                                                                   at java.lang.System.loadLibrary(System.java:988)
                                                                                                   at com.luajava.LuaState.<clinit>(LuaState.java:92)
                                                                                                   at com.luajava.LuaStateFactory.newLuaState(LuaStateFactory.java:59)
                                                                                                   at com.decapi.DecAPI.<clinit>(DecAPI.java:27)
                                                                                                   at com.youku.player.YoukuPlayerBaseApplication.onCreate(YoukuPlayerBaseApplication.java:35)
                                                                                                   at com.github.obsessive.simplifyreader.SimplifyReaderApplication.onCreate(SimplifyReaderApplication.java:38)
                                                                                                   at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
                                                                                                   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4553)
                                                                                                   at android.app.ActivityThread.access$1500(ActivityThread.java:151)
                                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
                                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                   at android.os.Looper.loop(Looper.java:135)
                                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                                   at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by William-Guan** [comment]
I have the same error. bad :(

**Comment by William-Guan** [comment]
这个libluajava.so文件是最新sdk里新添加的,需要去优酷平台上下载最新的sdk然后将缺少的so文件添加进去这个错误就解决了,之后就另一个问题就**接踵而来**了.

**Comment by elderSword** [comment]
我是在测试机上出现的问题，其他手机没有问题。

**Comment by shuangqingfeng** [comment]
您好！版主，可不可以解决下缺少 libluajava.so 的问题

**Comment by lfkang** [comment]
我也遇到了

**Comment by qq471077336** [comment]
应该是优酷更新了SDK，这个应用没更新

**Comment by Xanthuim** [comment]
但是这个是本地啊，更不更新有什么关系呢。博主哪儿去了。。。

**Comment by Xanthuim** [comment]
@William-Guan 请问具体在哪儿啊，优酷没找到啊
