### ISSUE TITLE
libluajava.so

### ISSUE THREAD

**Issue by hqucsx** [SkillCollege/SimplifyReader#7]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.github.obsessive.simplifyreader-1/base.apk"],nativeLibraryDirectories=[/data/app/com.github.obsessive.simplifyreader-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libluajava.so"
	at java.lang.Runtime.loadLibrary(Runtime.java:366)
	at java.lang.System.loadLibrary(System.java:989)
	at com.luajava.LuaState.<clinit>(LuaState.java:92)
	at com.luajava.LuaStateFactory.newLuaState(LuaStateFactory.java:59)
	at com.decapi.DecAPI.<clinit>(DecAPI.java:27)
	at com.youku.player.YoukuPlayerBaseApplication.onCreate(YoukuPlayerBaseApplication.java:35)
	at com.github.obsessive.simplifyreader.SimplifyReaderApplication.onCreate(SimplifyReaderApplication.java:38)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4545)
	at android.app.ActivityThread.access$1500(ActivityThread.java:147)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1353)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5250)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)

**Comment by ChadCSong** [comment]
Just remove the 'arm64-v8a' lib folder from the project. Because 64-bit device will find the .so library in 'arm64' folder when it was existed. Just remove it.

**Comment by Sausure** [comment]
why could i find the ‘'arm64-v8a' in from the project?
I just have the same issue...

**Comment by Sausure** [comment]
I find it and delete it,but the app still break..
error:
08-26 10:25:08.461  15887-15887/com.github.obsessive.simplifyreader.application E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.UnsatisfiedLinkError: Couldn't load luajava from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.github.obsessive.simplifyreader-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.github.obsessive.simplifyreader-1, /system/lib]]]: findLibrary returned null
            at java.lang.Runtime.loadLibrary(Runtime.java:355)
            at java.lang.System.loadLibrary(System.java:525)
            at com.luajava.LuaState.<clinit>(LuaState.java:92)
            at com.luajava.LuaStateFactory.newLuaState(LuaStateFactory.java:59)
            at com.decapi.DecAPI.<clinit>(DecAPI.java:27)
            at com.youku.player.YoukuPlayerBaseApplication.onCreate(YoukuPlayerBaseApplication.java:35)
            at com.github.obsessive.simplifyreader.SimplifyReaderApplication.onCreate(SimplifyReaderApplication.java:38)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4444)
            at android.app.ActivityThread.access$1300(ActivityThread.java:141)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5103)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by qianguming** [comment]
Process: com.github.obsessive.simplifyreader.application, PID: 4967
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.github.obsessive.simplifyreader-1/base.apk"],nativeLibraryDirectories=[/data/app/com.github.obsessive.simplifyreader-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libluajava.so"
            at java.lang.Runtime.loadLibrary(Runtime.java:366)
            at java.lang.System.loadLibrary(System.java:988)
            at com.luajava.LuaState.<clinit>(LuaState.java:92)
            at com.luajava.LuaStateFactory.newLuaState(LuaStateFactory.java:59)
            at com.decapi.DecAPI.<clinit>(DecAPI.java:27)
            at com.decapi.DecAPI.init(DecAPI.java:79)
            at com.youku.player.YoukuPlayerBaseApplication.onCreate(YoukuPlayerBaseApplication.java:35)
            at com.github.obsessive.simplifyreader.SimplifyReaderApplication.onCreate(SimplifyReaderApplication.java:38)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1017)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4858)
            at android.app.ActivityThread.access$1500(ActivityThread.java:178)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1531)
            at android.os.Handler.dispatchMessage(Handler.java:111)
            at android.os.Looper.loop(Looper.java:194)
            at android.app.ActivityThread.main(ActivityThread.java:5637)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
01-01 02:26:00.453    4994-4994/? E/AEE/LIBPARSE-PAGEMAP﹕ num_pages should be positive number

**Comment by ChadCSong** [comment]
@Sausure  Seems not a same question. Did you use a virtual device or Genymotion to run the app?

**Comment by Sausure** [comment]
@ChadCSong Yes，I use Genymotion，should't I use a virtual device?because my HongMi can run it.

**Comment by SkillCollege** [comment]
@Sausure  Yes，U should't use virtual device.

**Comment by Sausure** [comment]
@SkillCollege could you tell me why i should't use  virtual device?library do not support it?

**Comment by SkillCollege** [comment]
@Sausure  I guess U must be right

**Comment by Sausure** [comment]
@SkillCollege youku library?

**Comment by SkillCollege** [comment]
@Sausure yes

**Comment by Sausure** [comment]
@SkillCollege I learn more from your project ! thank you !!

**Comment by SkillCollege** [comment]
@Sausure  U can scan the Alipay QR code , tipping me for a cup of coffee!!

**Comment by SkillCollege** [comment]
@Sausure  Tks a lot !!! I got it

**Comment by Sausure** [comment]
@SkillCollege haha,sure.I am a student,and hope i can catch up you

**Comment by SkillCollege** [comment]
@Sausure  You can do it, fighting...

**Comment by ChadCSong** [comment]
@Sausure @SkillCollege Genymotion have some bugs on Arm lib support. To resolve this problem, you can use the x86 luajava lib or compile it yourself. There are many differences between cellphones and virtual devices, try to use a cellphone to run it. :)

**Comment by MrBigBang** [comment]
我是在真机上跑你提供的apk，安装好之后根本打不开，魅蓝note2,，系统android5.1

**Comment by xiaozhi003** [comment]
如果没有64位的so库，在编译的时候过滤掉就好了。64位的手机如果引用了so库，那么在编译的时候会自动生成arm-64的文件夹，调用的时候就会引用64位的so库。在gradle中添加如下语句过滤掉64位的文件夹
you can add it like this：
android {
  compileSdkVersion 23
  ...
  defaultConfig {
    ndk {
            abiFilters "armeabi", "armeabi-v7a", "x86"
       }
  }
}

**Comment by Wood-Water-Peng** [comment]
我也遇到了这个问题，一运行就崩溃，试了各位的说法,如过滤掉64位的文件夹，这样做连编译都不能通过啊，请教有没有新的解决办法啊

**Comment by ZhenMrLee** [comment]
工程里面的arm-64全部删了  就可以了
