### ISSUE TITLE
运行报错，log如下

### ISSUE THREAD

**Issue by GhRyuJin** [SkillCollege/SimplifyReader#72]
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                               Process: com.github.obsessive.simplifyreader.application, PID: 1700
                                                                                               de.greenrobot.event.EventBusException: Illegal onEvent method, check for typos: public void com.github.obsessive.simplifyreader.ui.fragment.MusicsFragment.onEventComming(com.github.obsessive.library.eventbus.EventCenter)
                                                                                                   at de.greenrobot.event.SubscriberMethodFinder.findSubscriberMethods(SubscriberMethodFinder.java:97)
                                                                                                   at de.greenrobot.event.EventBus.register(EventBus.java:163)
                                                                                                   at de.greenrobot.event.EventBus.register(EventBus.java:133)
                                                                                                   at com.github.obsessive.library.base.BaseLazyFragment.onCreate(BaseLazyFragment.java:84)
                                                                                                   at android.support.v4.app.Fragment.performCreate(Fragment.java:1951)
                                                                                                   at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1029)
                                                                                                   at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
                                                                                                   at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
                                                                                                   at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
                                                                                                   at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
                                                                                                   at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:141)
                                                                                                   at android.support.v4.view.ViewPager.populate(ViewPager.java:1177)
                                                                                                   at android.support.v4.view.ViewPager.populate(ViewPager.java:1025)
                                                                                                   at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1545)
                                                                                                   at android.view.View.measure(View.java:16497)
                                                                                                   at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:1071)
                                                                                                   at android.view.View.measure(View.java:16497)
                                                                                                   at android.widget.LinearLayout.measureVertical(LinearLayout.java:847)
                                                                                                   at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                                                                   at android.view.View.measure(View.java:16497)
                                                                                                   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                                                   at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                                                   at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
                                                                                                   at android.view.View.measure(View.java:16497)
                                                                                                   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                                                   at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
                                                                                                   at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                                                                   at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                                                                   at android.view.View.measure(View.java:16497)
                                                                                                   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                                                   at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                                                   at android.view.View.measure(View.java:16497)
                                                                                                   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                                                   at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
                                                                                                   at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                                                                   at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                                                                   at android.view.View.measure(View.java:16497)
                                                                                                   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                                                                   at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                                                                   at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2291)
                                                                                                   at android.view.View.measure(View.java:16497)
                                                                                                   at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1940)
                                                                                                   at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1137)
                                                                                                   at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1319)
                                                                                                   at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1024)
                                                                                                   at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5694)
                                                                                                   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
                                                                                                   at android.view.Choreographer.doCallbacks(Choreographer.java:574)
                                                                                                   at android.view.Choreographer.doFrame(Choreographer.java:544)
                                                                                                   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
                                                                                                   at android.os.Handler.handleCallback(Handler.java:733)
                                                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                                   at android.os.Looper.loop(Looper.java:136)
                                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5045)
                                                                                               	at java.lang.ref

**Comment by tan359449749** [comment]
i have the same question，have anyone can solve it？。

**Comment by 609685846** [comment]
一样的问题 有解么
